### ISSUE TITLE
range.contains() should not exclude start day of range with exclusive true

### ISSUE THREAD

**Issue by RossJHagan** [rotaready/moment-range#154]
Apologies if I've got some faulty assumptions about what it should do.  The .contains() method appears to be excluding the start date when you pass in the `{exclusive: true}` parameter.

I've put a jsbin demo up.

[Demo of problem](https://jsbin.com/ximifozere/edit?html,console)

Hope I've just misunderstood and sorry for wasting your time if so!

**Comment by JackDeMeyers** [comment]
It seems odd that the exclusive .contains() would **only** exclude the end and not the start, so the behavior in your jsbin, in my opinion, seems correct. However, you're right that the behavior is not as described in the docs. 

> The `exclusive` options is used to indicate if the **end** of the range should be excluded when testing for inclusion

Maybe the docs should be changed to say:

> The `exclusive` options is used to indicate if the **start** and **end** of the range should be excluded when testing for inclusion

Also, what is the difference between `.contains()` and `.within()`? Why are these separate?

**Comment by gf3** [comment]
@JackDeMeyers `within()` is [just an alias](https://github.com/rotaready/moment-range/blob/5b062deaa3ba2548f73f81b32a018c15f6adb110/lib/moment-range.js#L368-L373) to `contains()`. the difference being that `contains()` is available on date ranges and `within()` is available on moment objects (and they accept opposite parameters)

@RossJHagan looks like it [originally functioned as it is described in the docs](https://github.com/rotaready/moment-range/pull/65) but somewhere in the `3.0.0` update it was changed so that both the `start` and `end` were both excluded

### Proposed solution

deprecate the `exclusive` option and add two new options: `excludeStart` and `excludeEnd`. not only will it give others more control, it's easier to understand what the feature does

cc: @Rhysjc #174

**Comment by gf3** [comment]
Fixed in #208 / #214

**Comment by davidroman0O** [comment]
I was reading the issue to find if someone had the same problem or find a solution to my issue, maybe my bad.

But I'm in front of an issue OR i didn't really understand the usage of contains.

In yellow, it's the rangeA.
In red, the rangeB.
In green, the date I want to know if it's in each range or not.

Naturally, I made a `rangeA.contains(dateMoment, { excludeStart: true, excludeEnd: true })` for the rangeA and the date and `rangeB.contains(dateMoment, { excludeStart: true, excludeEnd: true })` because I know I don't want to include start and end.

So, where did I miss something ? 😄 

I should have `true` and `false`, right ? And not `false` and `false`, right ? 

Thx for your library and your time 😃 

<img width="864" alt="Capture d’écran, le 2019-09-18 à 23 19 30" src="https://user-images.githubusercontent.com/2845356/65210954-11699a00-da6b-11e9-8af7-5fa11a0b20a3.png">

**Comment by TristanJM** [comment]
> I was reading the issue to find if someone had the same problem or find a solution to my issue, maybe my bad.
> 
> But I'm in front of an issue OR i didn't really understand the usage of contains.
> 
> In yellow, it's the rangeA.
> In red, the rangeB.
> In green, the date I want to know if it's in each range or not.
> 
> Naturally, I made a `rangeA.contains(dateMoment, { excludeStart: true, excludeEnd: true })` for the rangeA and the date and `rangeB.contains(dateMoment, { excludeStart: true, excludeEnd: true })` because I know I don't want to include start and end.
> 
> So, where did I miss something ? 😄
> 
> I should have `true` and `false`, right ? And not `false` and `false`, right ?
> 
> Thx for your library and your time 😃
> 
> <img alt="Capture d’écran, le 2019-09-18 à 23 19 30" width="864" src="https://user-images.githubusercontent.com/2845356/65210954-11699a00-da6b-11e9-8af7-5fa11a0b20a3.png">

Hey @davidroman0O,

It appears to be behaving correctly to me:
Yellow range: `Sep 18 06:00-12:00`
Red range: `Sep 18 14:00-23:00`

Date: `Sep 18 06:00`

* This date **is not** in the Red range (obviously). So this correctly returns `false`.
* This date **is not** in the Yellow range when you set `excludeStart: true` because you've chosen to not include the start of the Yellow range. So this correctly returns `false`.
* The date **would be** in the Yellow range if you set `excludeStart: false` - feel free to try this and expect to see `true`.

If you still think this is incorrect, drop over the code you've used (with the example dates) and I'll try to replicate!

**Comment by lfernando-silva** [comment]
> > I was reading the issue to find if someone had the same problem or find a solution to my issue, maybe my bad.
> > But I'm in front of an issue OR i didn't really understand the usage of contains.
> > In yellow, it's the rangeA.
> > In red, the rangeB.
> > In green, the date I want to know if it's in each range or not.
> > Naturally, I made a `rangeA.contains(dateMoment, { excludeStart: true, excludeEnd: true })` for the rangeA and the date and `rangeB.contains(dateMoment, { excludeStart: true, excludeEnd: true })` because I know I don't want to include start and end.
> > So, where did I miss something ? 😄
> > I should have `true` and `false`, right ? And not `false` and `false`, right ?
> > Thx for your library and your time 😃
> > <img alt="Capture d’écran, le 2019-09-18 à 23 19 30" width="864" src="https://user-images.githubusercontent.com/2845356/65210954-11699a00-da6b-11e9-8af7-5fa11a0b20a3.png">
> 
> Hey @davidroman0O,
> 
> It appears to be behaving correctly to me:
> Yellow range: `Sep 18 06:00-12:00`
> Red range: `Sep 18 14:00-23:00`
> 
> Date: `Sep 18 06:00`
> 
> * This date **is not** in the Red range (obviously). So this correctly returns `false`.
> * This date **is not** in the Yellow range when you set `excludeStart: true` because you've chosen to not include the start of the Yellow range. So this correctly returns `false`.
> * The date **would be** in the Yellow range if you set `excludeStart: false` - feel free to try this and expect to see `true`.
> 
> If you still think this is incorrect, drop over the code you've used (with the example dates) and I'll try to replicate!

I had the same problem. Debugging, in my case, I realized the lib `.contains` only works for `Date`, `moment` or `MomentRange` instances, event if it is not necessary to create a moment range. So:

```js
const start = '2019-10-01 00:00:00'
const end = '2019-10-01 00:00:00'
const range1 = moment.range(start,end)

const dt = '2019-10-01 00:00:00'
console.log(range1.contains(dt)) // logs false

const dt2 = new Date('2019-10-01 00:00:00')
console.log(range1.contains(dt2)) // logs true

const dt3 = moment('2019-10-01 00:00:00')
console.log(range1.contains(dt3)) // logs true

```

Also, is interesting to check timezone, as in my case, it works but for UTC-3.
