### ISSUE TITLE
Project status - we're alive!

### ISSUE THREAD

**Issue by emauricio** [rotaready/moment-range#177]
Hi there, 
Just simple question, is the project still alive? :)
seems like a long time since last update.

**Comment by carlholloway** [comment]
Hi @emauricio

Yes! moment-range is very much alive. After many years of awesome work, @gf3 unfortunately no longer has time to maintain the project. We (here at Rotaready) are super excited and humbled to be taking on responsibility as of yesterday.

Over the coming days we'll start reviewing the issues and pull requests. We'll fix any bugs as a priority and then look at enhancements to ensure moment-range remains the best moment plugin for date range manipulation. We've had a long chat with @gf3 to ensure we follow his long term vision for the library going forwards.

If anyone has any feedback, please feel free to use this thread to put your thoughts across to us.

Cheers!

**Comment by emauricio** [comment]
as suggestion or idea.... will be nice if the project come by default with the ".d.ts" for typescript projects, i think it should be easy to create or maintain since this project already is using flow.

**Comment by AndreSteenveld** [comment]
@carlholloway Selfishly I'm here to ask if some of the PR's can be merged. What are the plans for the near future to keep the project running (merging/declining the PRs, dealing with the issues, etc). Is there anywhere that I (as a mere mortal ;) can get some information about the long term vision?

**Comment by carlholloway** [comment]
@AndreSteenveld Hey! We're on it :) There are many issues and PRs so at the moment it's a case of prioritisation and getting up to speed with it all. 

My aim is to get all the small fixes and quick wins rolled into a minor release over the next week or so. The bigger improvements will follow (our plan is to follow @gf3's lead and use "next version" branches to track longer running feature development so you can all test out new ideas and give feedback etc.)

**Comment by AndreSteenveld** [comment]
@carlholloway If there is anything I can do I'd like to contribute 4~6 hours in the next few weeks.

**Comment by sandstrom** [comment]
@AndreSteenveld I'm not the right person to answer, but personally I'm very excited about pretty formatting of date ranges. See this issue for more details: https://github.com/rotaready/moment-range/pull/131

Perhaps that's something you'd like to help out with?

**Comment by Rosensweig** [comment]
Hi everyone!  Glad to see this is being updated again.

I'm currently using moment-range to manipulate time for a scheduling app I'm creating. In the process, I've written functions to add and subtract arrays of time ranges (like a whole list of GCal events from their API). It wouldn't take much adaptation to make them a part of the whole package, rather than my own separate functions. I think it would be useful functionality for others, so I'd like to contribute that.

I'd also like to modify the `add()` function to allow adjacent as an option (just like the `overlaps()` function does). I had to create my own add function (for just two ranges) in the process of creating functionality to add arrays of ranges, because yours didn't include this. I think it should be at least an option to add, say 2-4 PM and 4-5 PM, and get back 2-5 PM rather than null. (Maybe even the default behavior if I were coding from scratch, but since people are already using it with existing behavior, making it an option is less likely to break existing code.)

Since you have a backlog of pull requests right now, would it make sense to wait a little bit before doing that, until you've handled some of the more pressing ones? It might avoid unnecessary merge conflicts, if I went in after those had been done.

**Comment by pronebel** [comment]
(My english is poor ~_~)

The Moment is too large and not used in many applications
Moment-range is a very good library.
I think the moment-range can be developed that is not dependent on moment.
The moment range  can be used by more developers.
It may be able to be adjusted from the architecture to facilitate the compilation of two of dependencies and dependencies

**Comment by pronebel** [comment]
The  address (https://github.com/pronebel/nb-date) is changed for my project.
I try change it not depend on the Moment, I find the most functions is ok. 
Some functions can be solved by tiny Libraries

**Comment by gf3** [comment]
moment-range has been on a steady release schedule for quite some time now. check out the newly released `4.0.0`! closing this issue for now. thanks everyone
