### ISSUE TITLE
just time comparsion

### ISSUE THREAD

**Issue by hassanrazakhalid** [rotaready/moment-range#196]
hello 
I have trying to just compare the time part. How ever i cannt seems to make it work
Does 'within'  works just time part. I have checked the values are not null. I am getting
Current Time = 04:40:00
StartTime =04:39:00
 EndTime = 04:50:00
Logically it should overlap.
         ```
   const startTime = moment(appointment.startDateTime, DBTimeformat);
            const endTime = moment(appointment.endDateTime, DBTimeformat);
            const range = moment.range(startTime, endTime);
            
           if ( currentTime.within(range) )  {
                    console.log('Overlap')
            }
```

**Comment by mkgn** [comment]
I have the same issue, If there was an option to just compare the time part that would be great. Right now I want to check whether times overlap (date can be same). At the moment it doesn't work.

**Comment by marty331** [comment]
This issue affects me as well, it would be great to check if time is within a range.

**Comment by TristanJM** [comment]
If you don't provide moment with a date, it will use today's date for the object.

If date is not important, you could easily set the date to the same arbitrary value so that moment-range just compares the times. This could even be done temporarily in a function just for the time comparison.


    const constDate = { year: 2000, month: 0, date: 1 };
    current = current.set(constDate);
    start = start.set(constDate);
    end = end.set(constDate);

    range = moment.range(start, end);
    current.within(range);  // true


I am not keen to add an option to compare times for a range because:
- Probably not a likely situation and has a very simple fix anyway (above).
- Doesn't make logical sense to pass a DateRange and compare the times but not dates - especially if the end time comes before the start time but on a different date.
