### ISSUE TITLE
Array.from(range.by('day')) throws an error

### ISSUE THREAD

**Issue by katsgeorgeek** [rotaready/moment-range#202]
Array.from(range.by('day')) throws an error in node.js env. It happens only after upgrade version to 3.1.3.

### System
node: v8.9.0 | v9.1.0
moment-range: 3.1.0

### Error
```
<--- Last few GCs --->

[3687:0x102801c00]    39261 ms: Mark-sweep 1353.2 (1418.6) -> 1351.6 (1421.6) MB, 784.2 / 0.0 ms  allocation failure GC in old space requested
[3687:0x102801c00]    39916 ms: Mark-sweep 1351.6 (1421.6) -> 1351.5 (1388.1) MB, 654.6 / 0.0 ms  last resort GC in old space requested
[3687:0x102801c00]    40606 ms: Mark-sweep 1351.5 (1388.1) -> 1351.5 (1387.1) MB, 690.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x335a16ca5ec1 <JSObject>
    2: from(aka from) [native array.js:1] [bytecode=0x335ab95ecb59 offset=225](this=0x335aeef02311 <undefined>,arrayLike=0x335aff7e0369 <Object map = 0x335a485d0909>,mapfn=0x335aeef02311 <undefined>,receiver=0x335aeef02311 <undefined>)
    3: arguments adaptor frame: 1->3
    5: /* anonymous */(aka /* anonymous */) [some path...]

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::Add(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 8: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
 9: v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::JSObject::AccessorInfoHandling) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
10: v8::internal::JSObject::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::ShouldThrow) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
11: v8::internal::Runtime_CreateDataProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/katsgeorgeek/.nvm/versions/node/v8.9.0/bin/node]
12: 0x1138fcfc6838
```

**Comment by TristanJM** [comment]
I can't replicate this issue, can you provide your code?

**Node v8.9.2**
Code:
`let range = moment.range('2015-01-01', '2015-01-03');

console.log(Array.from(range.by('day')));`

Output:
`[ moment("2015-01-01T00:00:00.000"),
  moment("2015-01-02T00:00:00.000"),
  moment("2015-01-03T00:00:00.000") ]`

**Comment by katsgeorgeek** [comment]
@TristanJM  yes, my bad v3.1.0.

Hm, I've tried to create an example and looks good. Right now I can only provide some hopefully helpful information e.g. 
"next": "^4.1.4",
"moment": "^2.19.2",
"moment-range": "^3.1.0",

Will try to make clear example a bit later

**Comment by dolma** [comment]
@katsgeorgeek 

I know this issue is a few weeks old, but I've just stumbled upon a similar error and it turns out it was just due to a typo. So maybe it would help you find the source of your problem if you didn't already.

Basically it happened because the iterator would go through millions of values and eventually run out of memory and crash when trying to allocate an Array with it.

This would happen if you, like I did, mistakenly created a range with only 1 date instead of 2, which would result into an "open-ended range".

**Note**: The problem exists because in the implementation it's not actually an open-ended range per se, it is just a regular range but the end date is really far away in the future (Sep 13 275,760 or 8,640,000,000,000,000 milliseconds) and that means the `by()` function will run as it would with any other range but have to go through a ton of days (approximately 100 million days) and saturate your memory.

2 simple ways to check if it's crashing for the same reason:

1. Try doing `your_range.diff('days')` to see how big your range is
2. Alternatively try checking the end date of your range: `your_range.end` and see how far away in the future it is

Hope this helps

**Comment by dolma** [comment]
@katsgeorgeek 

I know this issue is a few weeks old, but I've just stumbled upon a similar error and it turns out it was just due to a typo. So maybe it would help you find the source of your problem if you didn't already.

Basically it happened because the iterator would go through millions of values and eventually run out of memory and crash when trying to allocate an Array with it.

This would happen if you, like I did, mistakenly created a range with only 1 date instead of 2, which would result into an "open-ended range".

**Note**: The problem exists because in the implementation it's not actually an open-ended range per se, it is just a regular range but the end date is really far away in the future (Sep 13 275,760 or 8,640,000,000,000,000 milliseconds) and that means the `by()` function will run as it would with any other range but have to go through a ton of days (approximately 100 million days) and saturate your memory.

2 simple ways to check if it's crashing for the same reason:

1. Try doing `your_range.diff('days')` to see how big your range is
2. Alternatively try checking the end date of your range: `your_range.end` and see how far away in the future it is

Hope this helps
