### ISSUE TITLE
Exclude start is not working properly

### ISSUE THREAD

**Issue by AuspeXeu** [rotaready/moment-range#262]
Consider the following example
```
const range = moment.range(
  moment.utc("2019-05-20T09:00:00.000+00:00"),
  moment.utc("2019-05-21T17:30:00.000+00:00")
)
for (let day of range.by('days', {excludeEnd: true, excludeStart: true})) {
  console.log('iter', day)
}
```
Intuitively, this should not print anything since both, end and start are excluded. However, I get the following output.
```
iter moment.utc("2019-05-20T09:00:00.000+00:00")
```

**Comment by TristanJM** [comment]
Hey @AuspeXeu, `.by()` doesn't actually use the `excludeStart` flag, only the `excludeEnd`.
I can't remember exactly why this decision was made, but I'd imagine because it would be strange to iterate from index 1 and also would require some overhead to retrospectively trim the first element from the resulting iterator.

If you really need this functionality, I recommend just adding 1 period (`day`) to the start before doing the `range.by`

**Comment by TristanJM** [comment]
Feel free to re-open if you'd like to discuss further 😄

**Comment by AuspeXeu** [comment]
I guess I got confused by these mentions of `excludeStart`

![image](https://user-images.githubusercontent.com/2115696/66314979-e42e4000-e8e2-11e9-8fe0-c34caded1d18.png)

Maybe it should be pointed out in the documentation that `by` does not respect the `exludeStart` option?
